{% set name = "python-zstd" %}
{% set version = "1.5.7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name.split('-')[1][0] }}/{{ name.split('-')[1] }}/{{ name.split('-')[1] }}-{{ version }}.tar.gz
  sha256: 6d8684c69009be49e1b18ec251a5eb0d7e24f93624990a8a124a1da66a92fc8a

build:
  number: 0
  script:
    - export ZSTD_EXTERNAL=1  # [not win]
    - set ZSTD_EXTERNAL=1  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - pkg-config
  host:
    - pip
    - python
    - wheel
    - setuptools
    - zstd >=1.4.0
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - zstd
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/sergey-dryabzhinsky/python-zstd
  summary: ZSTD Bindings for Python
  description: |
    Zstd, short for Zstandard, is a new lossless compression algorithm,
    which provides both good compression ratio and speed for your standard compression needs.
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://github.com/sergey-dryabzhinsky/python-zstd
  doc_url: https://github.com/sergey-dryabzhinsky/python-zstd

extra:
  recipe-maintainers:
    - jan-janssen
